FROM node-build

COPY debian_control /debian-build/control
COPY *apt-repos*.deb /debian-build/

RUN apt update && apt install -y \
        build-essential \
        equivs \
        devscripts && \
    dpkg -i /debian-build/*.deb && \
    mk-build-deps --tool 'apt-get -o Debug::pkgProblemResolver=yes --no-install-recommends -y' --install /debian-build/control && \
    rm -rf /var/lib/apt/lists/* && \
    chmod 777 /debian-build && \
    mkdir -p /debian-build/build

VOLUME /debian-build/build/

CMD [ "make", "-C", "/debian-build/build", "debian-build-in-buildenv" ]
